import Link from 'next/link';
import Head from 'next/head';
import styled from 'styled-components';

import { LogoIcon } from '../public/assets/icons/logo';
import { Logo, LogoSizes } from '../src/components/logo/logo';
import {
  AnchorChildrens,
  AnchorHrefs,
  Anchors,
} from '../src/enumerations/anchors';

const Wrapper = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 44px;

  height: 100vh;
`;

export const StyledLogoIcon = styled(LogoIcon)`
  width: 116px;
  height: 116px;
`;

const Div = styled.div`
  display: flex;
  align-items: center;
  flex-direction: row;
  gap: 26px;
`;

const Button = styled.button`
  font-size: 20px;
  text-decoration: none;
  color: #1d1e24;

  padding: 16px 56px;

  border: 1px solid #1d1e24;
  border-radius: 50px;
`;

const Home = () => {
  return (
    <>
      <Head>
        <title>Task Manager</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Wrapper>
        <Logo size={LogoSizes.Medium} />

        <Div>
          {[Anchors.Authorization, Anchors.Registration].map((anchor) => {
            switch (anchor) {
              case Anchors.Authorization:
                return (
                  <Button
                    href={AnchorHrefs[anchor]}
                    children={AnchorChildrens[anchor]}
                    as={Link}
                  />
                );

              default:
                return (
                  <Button
                    href={AnchorHrefs[anchor]}
                    children={AnchorChildrens[anchor]}
                    as={Link}
                  />
                );
            }
          })}
        </Div>
      </Wrapper>
    </>
  );
};

export default Home;
